### ISSUE TITLE
Hook up hensel lifting functions?

### ISSUE THREAD

**Issue by Keno** [wbhart/Nemo.jl#106]
I noticed that FLINT has an implementation of hensel lifting in the `fmpz_poly_hensel_*` functions. I've been playing with some ideas in cryptography that make use of Hensel lifting so having these functions exposed to Julia would be fantastic.

**Comment by wbhart** [comment]
Hi Keno. This is just my private Nemo repository (see [1] for the official repo). I think this already wrapped in Hecke.jl, but I'm not sure. @thofma might know more, and I'll ask @fieker who is away at the moment, when he returns.

[1] https://github.com/Nemocas/Nemo.jl

**Comment by Keno** [comment]
Oh that's confusing, since that repo links to this one as the primary. Maybe ask GitHub to reverse the relationship among those repos? Thanks for taking a look.

**Comment by fieker** [comment]
If you go to the Hecke project (thofma/Hecke.jl), the has already happened. There are Juilia bindings for the lifting...
Furthermore, we've added lifting also over unramifed extensions

**Comment by Keno** [comment]
Thanks, I'll take a look.

**Comment by thofma** [comment]
See https://github.com/thofma/Hecke.jl/blob/c365b627aab19e1b168585664e9b2bb574de94a0/src/HeckeTypes.jl#L2026
and
https://github.com/thofma/Hecke.jl/blob/4263f1d414b52f79fd5e28e2f9a89d7536401917/src/Misc/Poly.jl#L201

**Comment by Keno** [comment]
I keep getting confused by the repo relation here. GitHub tries very hard to make the original repo stand out because of the parent relationship between the repos (e.g. the Nemocas version doesn't show up on Google at all because of it). It really would be better to have GitHub set the Nemocas one as canonical.
