### ISSUE TITLE
Apply Nemo.gamma on a vector

### ISSUE THREAD

**Issue by WT215** [wbhart/Nemo.jl#107]
Hello,

I would like to do the following:
 `CC = Nemo.ComplexField(64)` and `X=CC([1,2,3])`, then `Nemo.gamma.(X)`. Similar to `SpecialFunctions.gamma.([1,2,3])`.

In short, apply function from Nemo on a vector rather than just a scalar?

Thanks a lot!

**Comment by wbhart** [comment]
Hello,

Thanks for your suggestion, however the official Nemo project is here:

https://github.com/Nemocas/Nemo.jl

This is just my personal fork of Nemo here.

**Comment by WT215** [comment]
Oh sorry!
