### ISSUE TITLE
Conistency

### ISSUE THREAD

**Issue by thofma** [wbhart/Nemo.jl#17]
When we have algorithms for generic objects and concrete objects, should both have the same signature and return types?

For example, ```lufact(x::MatElem)``` will return ```rank, p, L, U``` while ```lufact(x::arb_mat)``` will return ```p, L, U```, because the input must be non-singular. Should I add the superfluous ```rank``` also for acb_mat so the interface is consistent?

**Comment by wbhart** [comment]
I guess in general the answer should be yes, for the sake of
metaprogramming, genericism.

Though it is hard to imagine a case where lufact is used in a generic way.

Bill.

**Comment by fredrik-johansson** [comment]
I'd say yes. By the way, it's a bit redundant for lufact to return the rank in the first place, since it can be computed easily from L.
