### ISSUE TITLE
Arb misconversion to Float64

### ISSUE THREAD

**Issue by JeffreySarnoff** [wbhart/Nemo.jl#47]
for example,
```
RR=ArbField(128);
x=RR("0.25");sx=sin(x);asx=asin(sx);
asx
[0.25000000000000000000000000000000000000 +/- 6.12e-39]
midpoint(asx)
[0.249999999999999999999999999999999999999 +/- 4.70e-40]
Float64(asx),Float64(midpoint(asx))
(0.24999999999999997,0.24999999999999997)
parse(Float64,"0.249999999999999999999999999999999999999")
0.25
```

**Comment by thofma** [comment]
Conversion of `arb` to `Float64` will return the midpoint of rounded down to a machine double.

There would be a misconversion if we claimed that we return the double which is closest to the midpoint.

**Comment by JeffreySarnoff** [comment]
Is there a reason that the conversion of arb to Float64 rounds down rather rounding to nearest?

**Comment by thofma** [comment]
For this we need to ask @fredrik-johansson

**Comment by fredrik-johansson** [comment]
Because rounding to the nearest double in arf_get_d wasn't supported in the past. It does work as of 2.8. Nemo just needs to be edited to call it with the ARF_RND_NEAR rounding mode.

**Comment by JeffreySarnoff** [comment]
That is good news, it allows better interaction between types.  If this is an acceptable change to Nemo, may I request it.

**Comment by thofma** [comment]
I made a pull request.

**Comment by wbhart** [comment]
I've merged the pull request.
