### ISSUE TITLE
cannot override show(io,x::arb) properly

### ISSUE THREAD

**Issue by JeffreySarnoff** [wbhart/Nemo.jl#52]
This is an issue for me, I don't know whether or not it is an issue for Nemo.
One expects redefining show(io::IO, x::arb) to change what is shown when an arb value is assigned.
That does not happen.  Explicitly typing show(variable) does engage the redefined show().  Just typing the name of the variable and pressing enter does not engage the redefined show().

I am trying to massage Arb into a state that better allows it to work easily with other Julia packages.  And I am doing that on top of the work that exists to make Arb available through Nemo.  The inability to automatically engage a redefined show is a real obstacle (I want to show the value as its midpoint rounded over +/- the radius by default, and use showall to present the midpoint and radius).

**Comment by wbhart** [comment]
Are you importing Base.show and exporting it again?

Note that Julia 0.5 issues a warning if you redefine functions.

**Comment by JeffreySarnoff** [comment]
Brilliant -- I had not known to re-export show after importing it. That works. Thank you.
