### ISSUE TITLE
regarding "cannot add methods to an abstract type"

### ISSUE THREAD

**Issue by Jeffrey-Sarnoff** [wbhart/Nemo.jl#53]
Julia v0.5 is not planning to carry support for adding methods to an abstract type [won't fix](https://github.com/JuliaLang/julia/issues/14919) 
(The issue remains open, which I interpret as desire for a more elegant and flexible solution.)   

The conflict in the current Nemo source appears to be confined to Poly.jl lines 1693-1711: when I comment out those lines, I can load and run Nemo in v0.5-dev.  

Are you planning a workaround to support v0.5?

**Comment by wbhart** [comment]
We are planning to support v0.5. We'll try and rescue what we can, but
obviously we might lose some functionality.

Bill.

**Comment by thofma** [comment]
Claus gave a shot at in his "five" branch. Here are the changes in Poly.jl: https://github.com/fieker/Nemo.jl/commit/bc01b9143a622582c5f5b6356cf81abaecbe1f27

With this change it works.

**Comment by wbhart** [comment]
Thanks. But won't this only work if this code is run after all the
polynomial types are loaded?

Perhaps we should put this in Nemo or Rings.jl after all the other files
have been included.

Bill.

**Comment by thofma** [comment]
Yes, I think you are right.

**Comment by wbhart** [comment]
I have added a fix for this, which is now merged.

By the way, please pull from and submit issues against the following repository from now on:

https://github.com/Nemocas/nemo.jl
