### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by JeffreySarnoff** [wbhart/Nemo.jl#97]
It seems the `==` in line 126 of arb_mat should be `!=`.

**Comment by thofma** [comment]
We want to print the "$r by $c matrix" only if one of the dimensions is zero (to have some output for this case). Otherwise the dimensions are implicitly given in the output.

P.S.: This is the wrong repository.

**Comment by JeffreySarnoff** [comment]
ok -- thanks for clarifying.
