### ISSUE TITLE
Avoid rebuilding Nemo on every update idea

### ISSUE THREAD

**Issue by chakravala** [wbhart/Nemo.jl#99]
Every time Nemo is updated, there is some compilation going on in the build. Is it necessary to do this on every single update, or could this possibly be made to happen less often by keeping the binaries stored in a separate location, where they would persist between package updates? This way, the build script would only have to check if the compiled binaries need to be recompiled from last time, and skip if it doesn't. This would make for faster updates in the package manager.

**Comment by thofma** [comment]
I don't know if a package is allowed to write something outside of its package directory.

**Comment by wbhart** [comment]
We ultimately intend to support downloading binaries instead of building from source. This should fix this issue.

By the way, this is not the official Nemo repository, but my personal one. The official one is Nemocas/Nemo.jl.
